### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nfstein**

### CODE REVIEW

**Comment by Olament** [comment]
Wow, this is amazing! Thank you for your work. Merged.

**Comment by nfstein** [comment]
Glad to help! I did some work awhile back doing scraping of reddit posts on r/mycology to try to compile data for a similar project. If you're interested I can try and find that code.

**Comment by Olament** [comment]
Interesting! I have considered use other data source (other than iNat) for my mushroom classifier before, but I am not sure about their accurarcy. I am wondering how do you ensure the label you got from r/mycology is the "ground-truth"?

**Comment by nfstein** [comment]
It wouldn't be, it would be essentially equivalent to the expertise of the
reddit r/mycology community.

**Pull request merged**
